### ISSUE TITLE
Reevaluation and Refactor of unaliased TES4 messages

### ISSUE THREAD

**Issue by pStyl3** [loot/oblivion#311]
This issue is the continuation of [issue 232](https://github.com/loot/oblivion/issues/232), but this time we want to discuss all the different localized messages within the Oblivion masterlist, that are not (yet) using anchors in the form of `&example`.

A good amount of messages can likely stay as they are, but other messages can evenly likely be refactored to use existing (or to be created) message anchors, or even be removed because they are outdated or the plugin in question is not locatable in any way.

Because of the sheer amount of plugins that have such messages assigned to them, this issue will only serve as the central hub to organize and link all individual issues, that will be opened to handle this. These issues will "group" plugin messages that are similar, to make it easier for us to reach conclusions as to what to do with them.

While working on this, it will likely be the best course of action, to always add missing `url`'s, in case plugins are missing them. Try your best to locate plugins, if the masterlist does not yet contain an `url` for the plugin in question. But if the plugin in question seems unlocatable, it will be reasonable to remove the plugin in question as a whole.

These issues will need to be resolved:
- [x] Reevaluate unaliased messages - [Obsolete](https://github.com/loot/oblivion/issues/312)
- [x] Reevaluate unaliased messages - [Corrupt](https://github.com/loot/oblivion/issues/313)
- [x] Reevaluate unaliased messages - [Wrye Bash](https://github.com/loot/oblivion/issues/314)
- [x] Reevaluate unaliased messages - [Version](https://github.com/loot/oblivion/issues/315)
- [x] Reevaluate unaliased messages - [Rename](https://github.com/loot/oblivion/issues/316)
- [x] Reevaluate unaliased messages - [Use](https://github.com/loot/oblivion/issues/317)
- [x] Reevaluate unaliased messages - [In-Compatible](https://github.com/loot/oblivion/issues/318)
- [x] Reevaluate unaliased messages - [Requires](https://github.com/loot/oblivion/issues/319)
- [x] Reevaluate unaliased messages - [Update](https://github.com/loot/oblivion/issues/320)
- [x] Reevaluate unaliased messages - [General](https://github.com/loot/oblivion/issues/321)

In case that someone finds, that a message should be handled through a different issue, that can of course be adjusted.

**Comment by sibir-ine** [comment]
Since we'll be dealing with a lot of entries in tackling this issue, it'd be worth sorting the entries we work on into sections if they aren't already to make the masterlist a bit more tidy.

**Comment by pStyl3** [comment]
Do you have suggesstions for different sections that could be used to tidy things up a bit?

**Comment by sibir-ine** [comment]
I think Mac added most (if not all) of the ones from the SSE masterlist, & I think they're more than sufficient. I've only ever needed to add one to the SSE masterlist.

**Comment by pStyl3** [comment]
Here are all main sections of the Oblivion masterlist:
```
###### Official Game Files ######
###### Unofficial Patches ######
###### Nehrim ######
###### Modding Tools - Generated Files ######
###### Resources ######
###### Fixes ######
###### User Interface ######
###### AudioVisual ######
###### AudioVisual - Animations & Physics ######
###### AudioVisual - Weather ######
###### Character Appearance - Body,face & hair ######
###### Character Appearance - NPCs ######
###### Encounters - Allies ######
###### Environment, Landscape & Flora ######
###### Gameplay - General ######
###### Gameplay - Character Classes & Races ######
###### Gameplay - Combat ######
###### Gameplay - Economy & Item Balance ######
###### Gameplay - Magic & Abilities ######
###### Gameplay - NPC Behaviour & Dialogue ######
###### Gameplay - Quests ######
###### Items ######
###### Locations - New Lands ######
###### Locations - New Structures & Landmarks ######
###### Location - Overhauls ######
###### Location - Player homes ######
###### Morroblivion ######
###### Francescos Creatures and Items V5 ######
###### Item interchange ######
###### (OOO) Oscuro's Oblivion Overhaul ######
###### (MMM) Martigen’s Monster Mod ######
###### (WAC) Waalx Animals & Creatures ######
###### FCOM: Convergence ######
###### Armamentarium ######
###### MOBS - Medieval Oblivion Equipment Balance System ######
###### (UL) Unique Landscapes ######
###### Unique Landscapes Compatibility Patches (ULE/ULM/ULS) ######
###### Better Cities ######
###### Open Cities ######
###### CM Partners Basic ######
```

And with sub-sections:
```
###### Official Game Files ######
###### Unofficial Patches ######
###### Nehrim ######
###### Modding Tools - Generated Files ######
###### Resources ######
  ### Cobl - Tweaks ###
  ### Cobl - Races ###
  ### Cobl - Patches & Extras ###
  # Old Version Files #
  ### MigMaster Script Resources ###
###### Fixes ######
###### User Interface ######
###### AudioVisual ######
###### AudioVisual - Animations & Physics ######
###### AudioVisual - Weather ######
###### Character Appearance - Body,face & hair ######
###### Character Appearance - NPCs ######
  ### Diverse Dremora Project ###
###### Encounters - Allies ######
###### Environment, Landscape & Flora ######
  ### New Roads and Bridges ###
  # NRB4 Patches #
  ### Roads of Cyrodiil ###
  # RoC Patches #
###### Gameplay - General ######
###### Gameplay - Character Classes & Races ######
  ### Race Balancing Project ###
  # RBP Optional Modules #
  # RBP Compatibility - Better Redguards #
  # RBP NPCDiversity #
  # RBP Additions - Less Annoying Magic Experience #
  # RBP Additions - OOO & MMM #
  # RBP Body Seam Reducer #
  # RBP Gamesettings Resetters #
###### Gameplay - Combat ######
###### Gameplay - Economy & Item Balance ######
###### Gameplay - Magic & Abilities ######
  ### (L.A.M.E) Less Annoying Magic Experience ###
  # LAME - Optional modules #
###### Gameplay - NPC Behaviour & Dialogue ######
###### Gameplay - Quests ######
  # Integration Addons #
  # CSV Addons #
  # Legacy Files #
###### Items ######
###### Locations - New Lands ######
  ### Chronicles of Reeb ###
###### Locations - New Structures & Landmarks ######
###### Location - Overhauls ######
###### Location - Player homes ######
###### Morroblivion ######
  ### Morroblivion - Optional files ###
  ### Morroblivion - Unofficial Patch ###
  ### Morroblivion - 3rd Party files ###
###### Francescos Creatures and Items V5 ######
  ### Fran's Old version plugins ###
###### Item interchange ######
###### (OOO) Oscuro's Oblivion Overhaul ######
  ### OOO Level Rate Options ###
  ### OOO Respawn Rate Options ###
  ### OOO Compatibility Options ###
  ### OOO Other Options ###
  ### OOO Add-ons for Full version Only ###
  ### OOO Add-ons for lite version Only ###
  ### OOO Shivering Isles ###
  ### OOO Creature Add-ons ###
  ### OOO Equipment Add-on ###
  ### OOO Extended ###
  ### OOO 3rd Party Patches and Addons ###
###### (MMM) Martigen’s Monster Mod ######
  ### MMM ESP Options ###
  ### MMM Optionals ###
  ### MMM Old version files ###
  ### MMM Optional Add-ons and Patches ###
###### (WAC) Waalx Animals & Creatures ######
  ### WAC Optional files ###
  ### WAC - Item & Loot Fix ###
  ### WAC Patches or Fixes ###
###### FCOM: Convergence ######
  ### FCOM - Optional Addons ###
  ### FCOM - Old version files ###
###### Armamentarium ######
  ### Armamentarium Old Versions ###
  ### Armamentarium Complete (Latest Version) ###
# These should all be tagged with Deactivate, NoMerge, and NPCFaces, and should have priority -2.
###### MOBS - Medieval Oblivion Equipment Balance System ######
###### (UL) Unique Landscapes ######
  # Afters for Landscape Group
  ### UL Ancient Redwoods (The Great Forest) ###
  ### UL Ancient Yews ###
  ### UL Arrius Creek ###
  ### UL Aspen Wood ###
  ### UL Beaches of Cyrodiil (The Lost Coast) ###
  ### UL Blackwood Forest ###
  ### UL Bravil Barrowfields ###
  ### UL Brena River Ravine ###
  ### UL Cheydinhal Falls ###
  ### UL Chorrol Hinterland ###
  ### UL Cliffs of Anvil ###
  ### UL Cloudtop Mountains ###
  ### UL Colovian Highlands ###
  ### UL The Dark Forest ###
  ### UL The Eastern Peaks ###
  ### UL Entius Gorge ###
  ### UL Fallenleaf Everglade ###
  ### UL The Heath ###
  ### UL Imperial Isle ###
  ### UL Jerall Glacier ###
  ### UL Lush Woodland (The Great Forest) ###
  ### UL Panther River ###
  ### UL River Ethe ###
  ### UL Rolling Hills ###
  ### UL Silverfish River Valley ###
  ### UL Skingrad Outskirts ###
  ### UL Snowdale ###
  ### UL Stendarr Valley ###
###### Unique Landscapes Compatibility Patches (ULE/ULM/ULS) ######
  # ULC Patches - AltStart Town Lindum #
  # ULC Patches - Amen'thalas Well House #
  # ULC Patches - Apachii Heroes Store #
  # ULC Patches - Atahnoral: The Wizard's Home #
  # ULC Patches - Better Cities #
  # ULC Patches - Blood & Mud #
  # ULC Patches - Castle Dracula #
  # ULC Patches - Castle Eltz #
  # ULC Patches - Castle Seaview #
  # ULC Patches - Chorrol Plateau #
  # ULC Patches - Country Home #
  # ULC Patches - Daggerfall Memories: Cybiades #
  # ULC Patches - (Dragon Captions) County Sutch: New Haven City #
  # ULC Patches - (Dragon Captions) County Sutch: Owl's Cove #
  # ULC Patches - (Dragon Captions) The Imperial City of Sutch Reborn #
  # ULC Patches - Duke Patrick's Combat Archery #
  # ULC Patches - Duke Patrick's Fortress Of FeaR #
  # ULC Patches - Eagle's Rest #
  # ULC Patches - Eastbrink Town #
  # ULC Patches - Elsweyr the Deserts of Anequina #
  # ULC Patches - English Billsburg #
  # ULC Patches - Et in Arkay Ego #
  # ULC Patches - Fighters Guild Quests #
  # ULC Patches - Frostcrag Reborn De-Isolated #
  # ULC Patches - Fuse's Snail Racing #
  # ULC Patches - GATES TO AESGAARD #
  # ULC Patches - Gift Of Kynareth #
  # ULC Patches - Goblinwatch Keep #
  # ULC Patches - Hammerfell: The Eastern Grasslands #
  # ULC Patches - Hentai's Lovely House #
  # ULC Patches - HENTAI MANIA 2 #
  # ULC Patches - Hoarfrost Castle #
  # ULC Patches - ImpeREAL Empire: Unique Forts #
  # ULC Patches - Integration: The Stranded Light #
  # ULC Patches - Kragenir's Death Quest #
  # ULC Patches - Leveler's Cheat #
  # ULC Patches - Lost Sword of the Ayleids #
  # ULC Patches - MOBS / OMOBS Medieval Oblivion Balance System #
  # ULC Patches - MTC Thieves Grotto #
  # ULC Patches - Naheema Player Home #
  # ULC Patches - Nic-V's Better Beggars #
  # ULC Patches - Oblivion Uncut #
  # ULC Patches - Open Cities Classic #
  # ULC Patches - Order of the Dragon (Orden des Drachen) #
  # ULC Patches - Oscuro's Oblivion Overhaul (OOO) #
  # ULC Patches - Pine Lodge #
  # ULC Patches - RealSwords Nord #
  # ULC Patches - Reaper's The Dark Tower #
  # ULC Patches - Reaper's Waterfront #
  # ULC Patches - Reclaiming Sancre Tor #
  # ULC Patches - Redcourt Castle #
  # ULC Patches - Region Revive: Lake Rumare #
  # ULC Patches - Roads of Cyrodiil #
  # ULC Patches - Sacryn's Shivering Store #
  # ULC Patches - Settlements of Cyrodiil: Clearwater Farms #
  # ULC Patches - Settlements of Cyrodiil: Legion Outposts #
  # ULC Patches - Settlements of Cyrodiil: Oranstad Township #
  # ULC Patches - Shezrie's Towns #
  # ULC Patches - Snow Line Lodge #
  # ULC Patches - Snowy Road To Bruma #
  # ULC Patches - The Dwarves Of The Mountain #
  # ULC Patches - The Jerall Mountain Compendium Patch #
  # ULC Patches - The Golden Arrow Archers Shop #
  # ULC Patches - The Golden Crest #
  # ULC Patches - The Griffon Fortress #
  # ULC Patches - The Hesu Mod Collection #
  # ULC Patches - The Lost Province of Zedar #
  # ULC Patches - The Lost Spires #
  # ULC Patches - The Orange Maple Inn #
  # ULC Patches - The Temple of Five Lanterns #
  # ULC Patches - The Warrior's Castle (Die Burg des Kriegers)
  # ULC Patches - Tollingbrook Hollow Home #
  # ULC Patches - TWMP Skyrim Improved #
  # ULC Patches - Unholy Cathedral #
  # ULC Patches - Windspear Tower #
  # ULC Patches - Zork Mod #
  # ULC Patches - Z's Skeleton Horse #
###### Better Cities ######
  ### Better Cities - Optional Files ###
  ### Better Cities - Optional Integration Files ###
  ### Better Cities - Patches ###
  # All Natural
  # Alternative Start Arrive by Ship
  # Cyrodiil Upgrade Overhaul
  # Dark Brotherhood Chronicles: Awakening
  # FCOM
  # Halcyon Island
  # Heart of the Dead
  # Immersive Interiors
  # Knightly Armory
  # Knights of the Nine
  # Nic-Vs Better Beggars
  # Oblivifall: Losing My Religion
  # Oblivion Collectible Cards
  # Oscuro's Oblivion Overhaul
  # Order of the Dragon
  # Reclaiming Sancre Tor
  # Roads of Cyrodiil
  # Ruined Tail's Tale
  # Skingrad Outer District
  # Tears of the Fiend
  # The Elder Council
  # The Lost Spires
  # Valley View Estate
  # Verona House: Bloodlines
  # Vvardenfell Imports
  # Werewolf - Legends of the North
  ### Better Cities - Imperial City Patches ###
  # Blood & Mud
  # Kragenir's Death Quest
  # Oblivion Uncut
  # Oscuro's Oblivion Overhaul
  # Origin of the Mages Guild
  # Reclaiming Sancre Tor
  # Roads of Cyrodiil
  # Sexlivion
  # Skyrim Nords
  # Thievery in the Imperial City
  # Waalx Animals & Creatures
  ### Better Cities - Old version files ###
  ### Better Cities - 3RD Party Patches ###
###### Open Cities ######
  ### Open Cities - Optional Files ###
  ### Open Cities Patches ###
  # Bravil Docks by Greg Simmonds - OC Patch
  # Clocks of Cyrodiil - OC Patch
  # DLC Frostcrag Spire (Wizard's Tower) - OC Patch
  # DLC Knights of the Nine - OC Patch
  # Midas Magic - OC Patch
###### CM Partners Basic ######
  ### Companion Vilja ###
  # FCOM Patches #
```

**Comment by MacSplody** [comment]
Done in https://github.com/loot/oblivion/commit/99e59024ef318b3545b4b3069b13abc55b2969a5

**Comment by pStyl3** [comment]
Thanks a lot to everyone contributing, this is a great achievement. 🥇
